# render.yaml
# Auto-deploy configuration for Render: Postgres DB, Flask API, and React UI

# 1) Managed Postgres database
# A free Render Postgres instance for your app

databases:
  - name: forex-bureau-db         # service name
    region: oregon                # choose same region as your services
    plan: free                    # free tier
    postgresVersion: 16           # Postgres version
    databaseName: forex_bureau    # internal DB name
    user: forex_user              # internal DB user

# 2) Flask API Web Service
services:
  - type: web
    name: forex-bureau-api
    env: python                     # Python runtime
    region: oregon                  # same region for private networking
    plan: starter                   # free web service tier
    branch: main                    # auto-deploy from `main`
    rootDir: server                 # `cd server` before running commands

    # Build: install deps, run migrations, seed data
    buildCommand: |
      pip install --upgrade pip && pip install -r requirements.txt
      alembic -c migrations/alembic.ini upgrade head
      python seed.py

    # Start: launch Flask via Gunicorn
    startCommand: PYTHONPATH=. gunicorn server.app:app

    # Environment variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: forex-bureau-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: "460afb43de33e919e8b02b35ed4c3e4465ec8c0fb3b7a5fe15f861b3278515c5"
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .

# 3) React Static Site for the frontend
staticSites:
  - type: static
    name: forex-bureau-ui
    region: oregon                  # match region
    plan: free                      # free static site tier
    branch: main                    # auto-deploy from `main`
    rootDir: client                 # `cd client` before building

    # Build and publish
    buildCommand: npm install && npm run build
    publishDirectory: build         # serve from client/build/

    # API base URL for your frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: https://forex-bureau-api.onrender.com
