# Forex Bureau - Free Tier Deployment
databases:
  - name: forex-bureau-db
    region: oregon
    plan: free
    databaseName: forex_bureau
    user: forex_user

services:
  # Backend API (Flask/Python)
  - type: web
    name: forex-bureau-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      # 1. Install dependencies from the project root
      pip install --upgrade pip &&
      pip install -r server/requirements.txt &&

      # 2. Run database migrations
      export FLASK_APP=server/app.py &&
      flask db upgrade &&

      # 3. Seed the database
      python server/seed.py
    startCommand: |
      # Launch production server via Gunicorn
      cd server &&
      PYTHONPATH=. gunicorn --bind 0.0.0.0:$PORT --workers=1 --threads=4 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: forex-bureau-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: "dreamflasdc3septeebb2b3eadc3ed4f8ec6c9fb3b7a57ed5fb51b327853bc5"
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: ./server/uploads

  # Frontend UI (React/Node)
  - type: web
    name: forex-bureau-ui
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      cd client &&
      npm install &&
      npm run build
    startCommand: |
      cd client &&
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://forex-bureau-api.onrender.com
      - key: PORT
        value: 3000
